name: ci

on:
  push:
    tags:
      - "v*"
    branches-ignore:
      - "master"
    paths:
      - "3rdparty/include/**"
      - "include/**"
      - "src/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "MAA.sln"
      - ".github/workflows/ci.yml"
      - "!**/*.md"
  pull_request:
    branches:
      - "dev"
    paths:
      - "3rdparty/include/**"
      - "include/**"
      - "src/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "MAA.sln"
      - "!**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger secondary workflows # ref: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY install
        env:
          GH_TOKEN: ${{ secrets.DAYDREAMER114_MGF_WORKFLOW }}
